# This is a basic workflow to help you get started with Actions

name: Cypress Tests

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - uses: actions/cache@v2
      #   id: yarn-and-build-cache
      #   with:
      #     path: |
      #       ~/.cache/Cypress
      #       ~/.cache/yarn/v6
      #       ~/.npm
      #       build
      #       node_modules
      #     key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node_modules-build-

      - name: Cypress install
        uses: cypress-io/github-action@v2

        with:
          # Disable running of tests within install job
          runTests: false

      - name: fuck
        run: ls

      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          if-no-files-found: error
          path: node_modules
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - uses: actions/cache@v2
      #   id: yarn-build-cache
      #   with:
      #     path: |
      #       node_modules
      #       ~/.cache/Cypress
      #       ~/.cache/yarn/v6
      #       ~/.npm
      #       build
      #     key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node_modules-build-

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: node_modules
          path: node_modules
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: yarn start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          record: true
          group: merge
          tag: ${{ github.event_name }}
          parallel: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # set the commit message to the pull request title
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
  jest-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
